const USERS_DATA = [
  {
    id: '8a555cd3-fef1-4151-8a83-234901077e77',
    firstName: 'Michael',
    lastName: 'Jackson',
    email: 'hello@gmail.com',
    exp: 200,
    totalExp: 0,
    totalSchoolPoint: 0,
    totalFreeTimePoint: 0,
    totalHealthPoint: 0,
    totalSocialLifePoint: 0,
    strengths: [],
    rewards: [],
    events: [],
    likes: [],
    tests: [],
  },
  {
    id: 'feda1076-fc8d-4a4a-868d-18b7ffd0e940',
    firstName: 'David',
    lastName: 'Doe',
    email: 'doe@gmail.com',
    totalExp: 0,
    totalSchoolPoint: 0,
    totalFreeTimePoint: 0,
    totalHealthPoint: 0,
    totalSocialLifePoint: 0,
    strengths: [],
    rewards: [],
    event: [],
    likes: [],
    tests: [],
  },
];

export default USERS_DATA;
